services:
  db:
    image: postgres:14.10
    restart: always
    environment:
      - POSTGRES_USER=tattle
      - POSTGRES_PASSWORD=weak_password
      - POSTGRES_DB=dau_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ~/data/dau/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db_gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  queue:
    image: rabbitmq@sha256:e2505f78d58dca8c372cde3930e4d6bee5e02ac9001ce85ece5a11df606c1fa3 # rabbitmq:3.12.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq
      - ./.docker/rabbitmq/logs:/var/log/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret-cookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Admin123"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  hash_worker:
    image: tattletech/feluda-operator-hash:worker-amd64-latest
    container_name: hash_worker
    depends_on:
      - queue
    environment:
      MQ_USERNAME: admin
      MQ_PASSWORD: Admin123
      MQ_HOST: rabbitmq
      AWS_ACCESS_KEY_ID: AKIAZEOQEMFTJS244746
      AWS_SECRET_ACCESS_KEY: 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
      AWS_BUCKET: staging.dau.tattle.co.in
      AWS_REGION: ap-south-1
    command:
      - /bin/sh
      - -c
      - |
        echo "sleep for 10sec"
        sleep 10 
        python -m worker.hash.hash_worker
