name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/dau-dashboard
          tags: ${{ steps.vars.outputs.sha_short }}

      #   - name: deploy to cluster
      #     uses: steebchen/kubectl@v2.0.0
      #     with: # defaults to latest kubectl binary version
      #       config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #       command: set image --record deployment/kosh-server kosh-server=tattletech/kosh-server:${{ steps.vars.outputs.sha_short }}
      #   - name: verify deployment
      #     uses: steebchen/kubectl@v2.0.0
      #     with:
      #       config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #       version: v1.21.0 # specify kubectl binary version explicitly
      #       command: rollout status deployment/kosh-server
